import {
  faharicars,
  familybank,
  gulfafricanbank,
  khushi,
  landmarkautoauction,
  lizazenterprisesltd,
  lolc,
  mogo,
  momentum,
  mycredit,
  ncba,
  nobeltradingltd,
  premierbank,
  sidian,
  simbacorp,
  yahyacarsLogo,
  am,
  almasifinancial,
  alsiddiquemotors,
  autoboxmotors,
  axismotors,
  canonmotors,
  carhouse,
  coopbank,
  enNbd,
  hakki,
  platinum,
} from "../../../assets/images/ourClients";


export const clients = [
  // Banks
  { id: 1, img: ncba, name: "NCBA", link: "#" },
  { id: 2, img: coopbank, name: "Coop Bank", link: "#" },
  { id: 3, img: sidian, name: "Sidian", link: "#" },
  { id: 4, img: familybank, name: "Family Bank", link: "#" },
  { id: 5, img: gulfafricanbank, name: "Gulfa African Bank", link: "#" },
  { id: 6, img: premierbank, name: "Premier Bank", link: "#" },

  // Microfinance / Fintech
  { id: 7, img: mogo, name: "Mogo", link: "#" },
  { id: 8, img: hakki, name: "Hakki", link: "#" },
  { id: 9, img: almasifinancial, name: "Almasi Financial", link: "#" },
  { id: 10, img: platinum, name: "Platinum Credit", link: "#" },
  { id: 11, img: enNbd, name: "ENBD", link: "#" },
  { id: 12, img: lolc, name: "LOLC", link: "#" },
  { id: 13, img: mycredit, name: "My Credit", link: "#" },
  { id: 14, img: momentum, name: "Momentum", link: "#" },
  { id: 15, img: am, name: "AM", link: "#" },
  { id: 16, img: khushi, name: "Khushi", link: "#" },

  // Showrooms / Auto Companies
  { id: 17, img: faharicars, name: "Fahari Cars", link: "#" },
  { id: 18, img: yahyacarsLogo, name: "Yahya Cars", link: "#" },
  { id: 19, img: landmarkautoauction, name: "Landmark Auto Auction", link: "#" },
  { id: 20, img: lizazenterprisesltd, name: "Liza Z Enterprises Ltd", link: "#" },
  { id: 21, img: alsiddiquemotors, name: "Al Siddique Motors", link: "#" },
  { id: 22, img: autoboxmotors, name: "Autobox Motors", link: "#" },
  { id: 23, img: axismotors, name: "Axis Motors", link: "#" },
  { id: 24, img: canonmotors, name: "Canon Motors", link: "#" },
  { id: 25, img: carhouse, name: "Car House", link: "#" },
  { id: 26, img: nobeltradingltd, name: "Nobel Trading Ltd", link: "#" },
];
